kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibp-prod
subjects:
- kind: ServiceAccount
  name: default
  namespace: ibp-prod
roleRef:
  kind: ClusterRole
  name: ibp-prod
  apiGroup: rbac.authorization.k8s.io

